---
squid_package_name: "squid"
squid_auth_package: "apache2-utils"
squid_service_name: "squid"
squid_user: "squid"
squid_group: "squid"
squid_ncsa_auth_path: "/usr/sbin/basic_ncsa_auth"
squid_certgen_path: "/usr/sbin/security_file_certgen"
